"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright: Ankitects Pty Ltd and contributors
License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetAddonInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_VERSION_FIELD_NUMBER: builtins.int
    ADDON_IDS_FIELD_NUMBER: builtins.int
    client_version: builtins.int
    @property
    def addon_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        client_version: builtins.int = ...,
        addon_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addon_ids", b"addon_ids", "client_version", b"client_version"]) -> None: ...

global___GetAddonInfoRequest = GetAddonInfoRequest

@typing.final
class GetAddonInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AddonInfo]: ...
    def __init__(
        self,
        *,
        info: collections.abc.Iterable[global___AddonInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info"]) -> None: ...

global___GetAddonInfoResponse = GetAddonInfoResponse

@typing.final
class AddonInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    MODIFIED_FIELD_NUMBER: builtins.int
    MIN_VERSION_FIELD_NUMBER: builtins.int
    MAX_VERSION_FIELD_NUMBER: builtins.int
    id: builtins.int
    modified: builtins.int
    min_version: builtins.int
    max_version: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        modified: builtins.int = ...,
        min_version: builtins.int = ...,
        max_version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "max_version", b"max_version", "min_version", b"min_version", "modified", b"modified"]) -> None: ...

global___AddonInfo = AddonInfo

@typing.final
class CheckForUpdateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    BUILDHASH_FIELD_NUMBER: builtins.int
    OS_FIELD_NUMBER: builtins.int
    INSTALL_ID_FIELD_NUMBER: builtins.int
    LAST_MESSAGE_ID_FIELD_NUMBER: builtins.int
    version: builtins.int
    buildhash: builtins.str
    os: builtins.str
    install_id: builtins.int
    last_message_id: builtins.int
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        buildhash: builtins.str = ...,
        os: builtins.str = ...,
        install_id: builtins.int = ...,
        last_message_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["buildhash", b"buildhash", "install_id", b"install_id", "last_message_id", b"last_message_id", "os", b"os", "version", b"version"]) -> None: ...

global___CheckForUpdateRequest = CheckForUpdateRequest

@typing.final
class CheckForUpdateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEW_VERSION_FIELD_NUMBER: builtins.int
    CURRENT_TIME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    LAST_MESSAGE_ID_FIELD_NUMBER: builtins.int
    new_version: builtins.str
    current_time: builtins.int
    message: builtins.str
    last_message_id: builtins.int
    def __init__(
        self,
        *,
        new_version: builtins.str | None = ...,
        current_time: builtins.int = ...,
        message: builtins.str | None = ...,
        last_message_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_message", b"_message", "_new_version", b"_new_version", "message", b"message", "new_version", b"new_version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_message", b"_message", "_new_version", b"_new_version", "current_time", b"current_time", "last_message_id", b"last_message_id", "message", b"message", "new_version", b"new_version"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_message", b"_message"]) -> typing.Literal["message"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_new_version", b"_new_version"]) -> typing.Literal["new_version"] | None: ...

global___CheckForUpdateResponse = CheckForUpdateResponse
