"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright: Ankitects Pty Ltd and contributors
License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CardId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CID_FIELD_NUMBER: builtins.int
    cid: builtins.int
    def __init__(
        self,
        *,
        cid: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cid", b"cid"]) -> None: ...

global___CardId = CardId

@typing.final
class CardIds(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CIDS_FIELD_NUMBER: builtins.int
    @property
    def cids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        cids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cids", b"cids"]) -> None: ...

global___CardIds = CardIds

@typing.final
class Card(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NOTE_ID_FIELD_NUMBER: builtins.int
    DECK_ID_FIELD_NUMBER: builtins.int
    TEMPLATE_IDX_FIELD_NUMBER: builtins.int
    MTIME_SECS_FIELD_NUMBER: builtins.int
    USN_FIELD_NUMBER: builtins.int
    CTYPE_FIELD_NUMBER: builtins.int
    QUEUE_FIELD_NUMBER: builtins.int
    DUE_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    EASE_FACTOR_FIELD_NUMBER: builtins.int
    REPS_FIELD_NUMBER: builtins.int
    LAPSES_FIELD_NUMBER: builtins.int
    REMAINING_STEPS_FIELD_NUMBER: builtins.int
    ORIGINAL_DUE_FIELD_NUMBER: builtins.int
    ORIGINAL_DECK_ID_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    ORIGINAL_POSITION_FIELD_NUMBER: builtins.int
    MEMORY_STATE_FIELD_NUMBER: builtins.int
    DESIRED_RETENTION_FIELD_NUMBER: builtins.int
    DECAY_FIELD_NUMBER: builtins.int
    LAST_REVIEW_TIME_SECS_FIELD_NUMBER: builtins.int
    CUSTOM_DATA_FIELD_NUMBER: builtins.int
    id: builtins.int
    note_id: builtins.int
    deck_id: builtins.int
    template_idx: builtins.int
    mtime_secs: builtins.int
    usn: builtins.int
    ctype: builtins.int
    queue: builtins.int
    due: builtins.int
    interval: builtins.int
    ease_factor: builtins.int
    reps: builtins.int
    lapses: builtins.int
    remaining_steps: builtins.int
    original_due: builtins.int
    original_deck_id: builtins.int
    flags: builtins.int
    original_position: builtins.int
    desired_retention: builtins.float
    decay: builtins.float
    last_review_time_secs: builtins.int
    custom_data: builtins.str
    @property
    def memory_state(self) -> global___FsrsMemoryState: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        note_id: builtins.int = ...,
        deck_id: builtins.int = ...,
        template_idx: builtins.int = ...,
        mtime_secs: builtins.int = ...,
        usn: builtins.int = ...,
        ctype: builtins.int = ...,
        queue: builtins.int = ...,
        due: builtins.int = ...,
        interval: builtins.int = ...,
        ease_factor: builtins.int = ...,
        reps: builtins.int = ...,
        lapses: builtins.int = ...,
        remaining_steps: builtins.int = ...,
        original_due: builtins.int = ...,
        original_deck_id: builtins.int = ...,
        flags: builtins.int = ...,
        original_position: builtins.int | None = ...,
        memory_state: global___FsrsMemoryState | None = ...,
        desired_retention: builtins.float | None = ...,
        decay: builtins.float | None = ...,
        last_review_time_secs: builtins.int | None = ...,
        custom_data: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_decay", b"_decay", "_desired_retention", b"_desired_retention", "_last_review_time_secs", b"_last_review_time_secs", "_memory_state", b"_memory_state", "_original_position", b"_original_position", "decay", b"decay", "desired_retention", b"desired_retention", "last_review_time_secs", b"last_review_time_secs", "memory_state", b"memory_state", "original_position", b"original_position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_decay", b"_decay", "_desired_retention", b"_desired_retention", "_last_review_time_secs", b"_last_review_time_secs", "_memory_state", b"_memory_state", "_original_position", b"_original_position", "ctype", b"ctype", "custom_data", b"custom_data", "decay", b"decay", "deck_id", b"deck_id", "desired_retention", b"desired_retention", "due", b"due", "ease_factor", b"ease_factor", "flags", b"flags", "id", b"id", "interval", b"interval", "lapses", b"lapses", "last_review_time_secs", b"last_review_time_secs", "memory_state", b"memory_state", "mtime_secs", b"mtime_secs", "note_id", b"note_id", "original_deck_id", b"original_deck_id", "original_due", b"original_due", "original_position", b"original_position", "queue", b"queue", "remaining_steps", b"remaining_steps", "reps", b"reps", "template_idx", b"template_idx", "usn", b"usn"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_decay", b"_decay"]) -> typing.Literal["decay"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_desired_retention", b"_desired_retention"]) -> typing.Literal["desired_retention"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_review_time_secs", b"_last_review_time_secs"]) -> typing.Literal["last_review_time_secs"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_memory_state", b"_memory_state"]) -> typing.Literal["memory_state"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_original_position", b"_original_position"]) -> typing.Literal["original_position"] | None: ...

global___Card = Card

@typing.final
class FsrsMemoryState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STABILITY_FIELD_NUMBER: builtins.int
    DIFFICULTY_FIELD_NUMBER: builtins.int
    stability: builtins.float
    difficulty: builtins.float
    def __init__(
        self,
        *,
        stability: builtins.float = ...,
        difficulty: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["difficulty", b"difficulty", "stability", b"stability"]) -> None: ...

global___FsrsMemoryState = FsrsMemoryState

@typing.final
class UpdateCardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARDS_FIELD_NUMBER: builtins.int
    SKIP_UNDO_ENTRY_FIELD_NUMBER: builtins.int
    skip_undo_entry: builtins.bool
    @property
    def cards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Card]: ...
    def __init__(
        self,
        *,
        cards: collections.abc.Iterable[global___Card] | None = ...,
        skip_undo_entry: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cards", b"cards", "skip_undo_entry", b"skip_undo_entry"]) -> None: ...

global___UpdateCardsRequest = UpdateCardsRequest

@typing.final
class RemoveCardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARD_IDS_FIELD_NUMBER: builtins.int
    @property
    def card_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        card_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["card_ids", b"card_ids"]) -> None: ...

global___RemoveCardsRequest = RemoveCardsRequest

@typing.final
class SetDeckRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARD_IDS_FIELD_NUMBER: builtins.int
    DECK_ID_FIELD_NUMBER: builtins.int
    deck_id: builtins.int
    @property
    def card_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        card_ids: collections.abc.Iterable[builtins.int] | None = ...,
        deck_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["card_ids", b"card_ids", "deck_id", b"deck_id"]) -> None: ...

global___SetDeckRequest = SetDeckRequest

@typing.final
class SetFlagRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARD_IDS_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    flag: builtins.int
    @property
    def card_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        card_ids: collections.abc.Iterable[builtins.int] | None = ...,
        flag: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["card_ids", b"card_ids", "flag", b"flag"]) -> None: ...

global___SetFlagRequest = SetFlagRequest
