"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright: Ankitects Pty Ltd and contributors
License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SetTagCollapsedRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    COLLAPSED_FIELD_NUMBER: builtins.int
    name: builtins.str
    collapsed: builtins.bool
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        collapsed: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collapsed", b"collapsed", "name", b"name"]) -> None: ...

global___SetTagCollapsedRequest = SetTagCollapsedRequest

@typing.final
class TagTreeNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    COLLAPSED_FIELD_NUMBER: builtins.int
    name: builtins.str
    level: builtins.int
    collapsed: builtins.bool
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TagTreeNode]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        children: collections.abc.Iterable[global___TagTreeNode] | None = ...,
        level: builtins.int = ...,
        collapsed: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "collapsed", b"collapsed", "level", b"level", "name", b"name"]) -> None: ...

global___TagTreeNode = TagTreeNode

@typing.final
class ReparentTagsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAGS_FIELD_NUMBER: builtins.int
    NEW_PARENT_FIELD_NUMBER: builtins.int
    new_parent: builtins.str
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        new_parent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["new_parent", b"new_parent", "tags", b"tags"]) -> None: ...

global___ReparentTagsRequest = ReparentTagsRequest

@typing.final
class RenameTagsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_PREFIX_FIELD_NUMBER: builtins.int
    NEW_PREFIX_FIELD_NUMBER: builtins.int
    current_prefix: builtins.str
    new_prefix: builtins.str
    def __init__(
        self,
        *,
        current_prefix: builtins.str = ...,
        new_prefix: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_prefix", b"current_prefix", "new_prefix", b"new_prefix"]) -> None: ...

global___RenameTagsRequest = RenameTagsRequest

@typing.final
class NoteIdsAndTagsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOTE_IDS_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    tags: builtins.str
    @property
    def note_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        note_ids: collections.abc.Iterable[builtins.int] | None = ...,
        tags: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["note_ids", b"note_ids", "tags", b"tags"]) -> None: ...

global___NoteIdsAndTagsRequest = NoteIdsAndTagsRequest

@typing.final
class FindAndReplaceTagRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOTE_IDS_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    REPLACEMENT_FIELD_NUMBER: builtins.int
    REGEX_FIELD_NUMBER: builtins.int
    MATCH_CASE_FIELD_NUMBER: builtins.int
    search: builtins.str
    replacement: builtins.str
    regex: builtins.bool
    match_case: builtins.bool
    @property
    def note_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        note_ids: collections.abc.Iterable[builtins.int] | None = ...,
        search: builtins.str = ...,
        replacement: builtins.str = ...,
        regex: builtins.bool = ...,
        match_case: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["match_case", b"match_case", "note_ids", b"note_ids", "regex", b"regex", "replacement", b"replacement", "search", b"search"]) -> None: ...

global___FindAndReplaceTagRequest = FindAndReplaceTagRequest

@typing.final
class CompleteTagRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_FIELD_NUMBER: builtins.int
    MATCH_LIMIT_FIELD_NUMBER: builtins.int
    input: builtins.str
    """a partial tag, optionally delimited with ::"""
    match_limit: builtins.int
    def __init__(
        self,
        *,
        input: builtins.str = ...,
        match_limit: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["input", b"input", "match_limit", b"match_limit"]) -> None: ...

global___CompleteTagRequest = CompleteTagRequest

@typing.final
class CompleteTagResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAGS_FIELD_NUMBER: builtins.int
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tags", b"tags"]) -> None: ...

global___CompleteTagResponse = CompleteTagResponse
